services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1010"
      POSTGRES_DB: "teddydb"
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy-finance-api
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src