services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1010"  # only development environment
      POSTGRES_DB: "teddydb"  # only development environment
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
     - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy-finance-api
    restart: always
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgresql://postgres:1010@db:5432/teddydb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=1230-123-1jd12-0dj12-d1m2-dm12-dmn12dm-1
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
        
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090' 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-data: