services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1010"  # only development environment
      POSTGRES_DB: "teddydb"  # only development environment
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy-finance-api
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://postgres:1010@db:5432/teddydb
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src